version: '3.9'
services:
  web:
    build: 
      context: .
      dockerfile: docker/flask/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    restart: always
  
  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
      - redis
    restart: always
  
  redis:
    image: redis:7.0
    restart: always

  caddy:
    image: caddy:2.6.4
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config: